url:
  book: https://www.railstutorial.org/book
  contact: https://www.railstutorial.org/contact
  gravatar: https://secure.gravatar.com/avatar/
  help: https://www.railstutorial.org/help
  learnenough: https://www.learnenough.com
  michaelhartl: https://www.michaelhartl.com
  news: https://news.railstutorial.org
  railstut: https://www.railstutorial.org
  ror: https://rubyonrails.org
  screencasts: https://screencasts.railstutorial.org
user:
  email:
    length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  name:
    length: 50
  password:
    length: 6
