url:
  railstut: https://www.railstutorial.org
  book: https://www.railstutorial.org/book
  contact: https://www.railstutorial.org/contact
  help: https://www.railstutorial.org/help
  learnenough: https://www.learnenough.com
  screencasts: https://screencasts.railstutorial.org
  ror: https://rubyonrails.org
